language: java

sudo: required

jdk:
  - oraclejdk8

before_install:
  - wget https://archive.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.zip
  - unzip -qq apache-maven-3.3.9-bin.zip
  - export M2_HOME=$PWD/apache-maven-3.3.9
  - export PATH=$M2_HOME/bin:$PATH
  - export MAVEN_OPTS="-Xmx3096m -XX:MaxPermSize=1024m"
  - export JAVA_OPTS="-Xms256m -Xmx2048m"
  - mvn -vv

install:
  - mvn clean

script:
  - mvn test jacoco:report -Pcoverage -e

after_success:
  - mvn coveralls:report -Pcoverage

after_failure:
  - ./collect_crash_info.sh
